apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocdigx-app-mq
  labels:
    app: ocdigx-app-mq
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ocdigx-app-mq
  template:
    metadata:
      labels:
        app: ocdigx-app-mq
    spec:
      containers:
        - name: ocdigx-app-mq
          image: "karthickconnects/ocdigx:mq.3"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: serve
      imagePullSecrets:
        - name: karthickconnects
---
apiVersion: v1
kind: Service
metadata:
  name: ocdigx-app-mq-svc
  labels:
    app: ocdigx-app-mq-svc
spec:
  type: ClusterIP
  ports:
  - name: ocdigx-app-mq
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ocdigx-app-mq
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ocdigx-app-mq-route
  labels:
    app: ocdigx-app-mq-svc
spec:
  # hostname: foo.apps.CLUSTER.ccs.ornl.gov
  port:
    targetPort: ocdigx-app-mq
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ocdigx-app-mq-svc
    weight: 100
  wildcardPolicy: None